"""initial migration

Revision ID: 510803b36503
Revises: 
Create Date: 2024-03-19 18:01:36.235743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '510803b36503'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('tale', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stories_description'), 'stories', ['description'], unique=False)
    op.create_index(op.f('ix_stories_tale'), 'stories', ['tale'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stories_tale'), table_name='stories')
    op.drop_index(op.f('ix_stories_description'), table_name='stories')
    op.drop_table('stories')
    # ### end Alembic commands ###
